### ISSUE TITLE
Strange exception caused by epsagon

### ISSUE THREAD

**Issue by imshashank** [epsagon/epsagon-java#36] opened 2019-11-06 11:51 UTC
This is the entry in my cloudwatch logs:

```
{
  "timeMillis": 1573040263731,
  "thread": "main",
  "level": "ERROR",
  "loggerName": "com.epsagon.EpsagonRequestHandler",
  "message": "https://us-east-1.tc.epsagon.com",
  "endOfBatch": false,
  "loggerFqcn": "org.apache.logging.log4j.spi.AbstractLogger",
  "contextMap": {
    "AWSRequestId": "d4dddfb2-ab73-5982-ae7b-898e19b4aadb"
  },
  "threadId": 1,
  "threadPriority": 5
} 
```
This is the exception in cloudwatch logs

```
org/apache/logging/log4j/core/impl/ThrowableProxy$CacheEntry: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/impl/ThrowableProxy$CacheEntry
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toCacheEntry(ThrowableProxy.java:634)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:674)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:338)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy.<init>(Log4jLogEvent.java:921)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:697)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.createMemento(MutableLogEvent.java:459)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.convertMutableToLog4jEvent(AbstractJacksonLayout.java:118)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:124)
	at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:1028)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:104)
	at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:804)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:34)
	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:301)
	at com.amazonaws.services.lambda.runtime.log4j2.LambdaAppender.append(LambdaAppender.java:72)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733)
	at com.epsagon.Trace.send(Trace.java:147)
	at com.epsagon.EpsagonRequestHandler.handleRequest(EpsagonRequestHandler.java:68)
```

**Comment by galbash** [comment] 2019-11-07 11:44
Hi, you should have another entry in the CloudWatch starting with "Cannot connect to Trace collector URL". do you have one? it should contain the exception that caused this error.

**Comment by imshashank** [comment] 2019-11-08 07:05
No entry as such for that. This is the entry right before the exception

```
{
  "timeMillis": 1573195933853,
  "thread": "main",
  "level": "INFO",
  "loggerName": "com.epsagon.EpsagonRequestHandler",
  "message": "sending trace",
  "endOfBatch": false,
  "loggerFqcn": "org.apache.logging.log4j.spi.AbstractLogger",
  "contextMap": {
    "AWSRequestId": "bebc83f1-5f0d-55ff-812d-d5ce4dda52ca"
  },
  "threadId": 1,
  "threadPriority": 5
} 

{
  "timeMillis": 1573195933853,
  "thread": "main",
  "level": "ERROR",
  "loggerName": "com.epsagon.EpsagonRequestHandler",
  "message": "https://us-east-1.tc.epsagon.com",
  "endOfBatch": false,
  "loggerFqcn": "org.apache.logging.log4j.spi.AbstractLogger",
  "contextMap": {
    "AWSRequestId": "bebc83f1-5f0d-55ff-812d-d5ce4dda52ca"
  },
  "threadId": 1,
  "threadPriority": 5
} 
```

And after that the error->

```
org/apache/logging/log4j/core/impl/ThrowableProxy$CacheEntry: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/impl/ThrowableProxy$CacheEntry
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toCacheEntry(ThrowableProxy.java:634)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:674)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:338)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy.<init>(Log4jLogEvent.java:921)
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:697)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.createMemento(MutableLogEvent.java:459)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.convertMutableToLog4jEvent(AbstractJacksonLayout.java:118)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:124)
	at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:1028)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:104)
	at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:804)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:34)
	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:301)
	at com.amazonaws.services.lambda.runtime.log4j2.LambdaAppender.append(LambdaAppender.java:72)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733)
	at com.epsagon.Trace.send(Trace.java:147)
	at com.epsagon.EpsagonRequestHandler.handleRequest(EpsagonRequestHandler.java:68)

```



Please feel free to log into my account on epsagon and have look at the exception there.

**Comment by galbash** [comment] 2019-11-17 11:35
I couldn't reproduce it on my machine, but I created #46 that might do the trick. can you try it and let me know?

**Comment by galbash** [comment] 2019-11-18 08:51
version 1.4.5 should be released soon, which includes #46 . I expect that now we will be able to understand the real error that was raised. Is there any way the Lambda you tried this with is running in a VPC?

**Comment by galbash** [comment] 2019-11-18 08:52
closed by accident

**Comment by imshashank** [comment] 2019-11-20 06:54
The lambda is not running in a VPC.

**Comment by galbash** [comment] 2019-11-20 08:06
hi @imshashank , did the new version (1.4.5) fix this issue for you?

**Comment by galbash** [comment] 2019-11-20 08:08
hi @imshashank  , i saw in the other issue that you will attempt a deploy next week. I am closing this issue in the meantime, feel free to reopen if the new version (1.4.5) doesn't resolve it :)

**Closed by galbash** 2019-11-20 08:08 UTC
